#!/usr/bin/env bash

# Script to recreate a package from installed files
# Author: Tales A. Mendonça (talesam@gmail.com)
# Version: 1.1.0
# Date: $(date +%Y-%m-%d)

# Color definitions for status messages
blueDark="\e[1;38;5;33m"     # Bold dark blue
mediumBlue="\e[1;38;5;32m"   # Bold medium blue
lightBlue="\e[1;38;5;39m"    # Bold light blue
cyan="\e[1;38;5;45m"         # Bold cyan
white="\e[1;97m"             # Bold white
reset="\e[0m"                # Reset text formatting

# Additional colors for warnings/errors
red="\e[1;31m"               # Bold red for errors
yellow="\e[1;33m"            # Bold yellow for warnings
green="\e[1;32m"             # Bold green for success

# Print status messages
printMsg() {
    local message="$1"
    echo -e "${blueDark}[${lightBlue}PACKAGE${blueDark}]${reset} ${cyan}→${reset} ${white}${message}${reset}"
}

# Print success messages
printOk() {
    local message="$1"
    echo -e "${blueDark}[${green}SUCCESS${blueDark}]${reset} ${cyan}→${reset} ${white}${message}${reset}"
}

# Print warning messages
printWarn() {
    local message="$1"
    echo -e "${blueDark}[${yellow}WARNING${blueDark}]${reset} ${cyan}→${reset} ${white}${message}${reset}"
}

# Print error messages
printErr() {
    local message="$1"
    echo -e "${blueDark}[${red}ERROR${blueDark}]${reset} ${cyan}→${reset} ${white}${message}${reset}"
}

# Check if the user provided a package name
if [ -z "$1" ]; then
    printErr "No package name provided."
    echo "Usage: $0 package_name"
    exit 1
fi

package="$1"

# Temporary working directory
workDir="$HOME/recreate_package_$package"

# Directory to store recreated packages
outputDir="$HOME/recreated_packages"

pkgDir="$workDir/pkg"
fileList="$workDir/file_list.txt"
relativeFileList="$workDir/relative_file_list.txt"
pkgInfo="$pkgDir/.PKGINFO"
mTree="$pkgDir/.MTREE"

printMsg "Recreating package '$package'..."

# Step 1: Check if the package is installed
if ! pacman -Q "$package" &>/dev/null; then
    printErr "Package '$package' is not installed on the system."
    exit 1
fi

# Create working directory and output directory
mkdir -p "$pkgDir"
mkdir -p "$outputDir"

# Step 2: List all files installed by the package
printMsg "Listing files installed by the package..."
pacman -Qlq "$package" >"$fileList"
if [ $? -ne 0 ]; then
    printErr "Error listing package files."
    exit 1
fi

# Create list of files with relative paths
sed 's|^/||' "$fileList" >"$relativeFileList"

# Step 3: Copy files to the pkg directory using sudo
printMsg "Copying files to the packaging directory..."
totalSize=0
while IFS= read -r file; do
    if [ -f "/$file" ]; then
        dir=$(dirname "$file")
        sudo mkdir -p "$pkgDir/$dir"
        sudo cp -a "/$file" "$pkgDir/$dir/"
        fileSize=$(du -b "/$file" | cut -f1)
        totalSize=$((totalSize + fileSize))
        echo -e "${mediumBlue}Copied:${white} /$file ($(numfmt --to=iec-i --suffix=B --format="%.2f" $fileSize))${reset}"
    elif [ -d "/$file" ]; then
        sudo mkdir -p "$pkgDir/$file"
        echo -e "${mediumBlue}Created directory:${white} /$file${reset}"
    fi
done <"$relativeFileList"

echo -e "${mediumBlue}Total size of copied files:${white} $(numfmt --to=iec-i --suffix=B --format="%.2f" $totalSize)${reset}"

# Adjust permissions of copied files to the current user
sudo chown -R $(whoami):$(whoami) "$pkgDir"

# Step 4: Create the .PKGINFO file
printMsg "Creating .PKGINFO file..."
# Use LANG=C to ensure pacman output is in English
pkgVer=$(LANG=C pacman -Qi "$package" | grep "^Version" | awk '{print $3}')
pkgDesc=$(LANG=C pacman -Qi "$package" | grep "^Description" | cut -d ':' -f2- | sed 's/^ //')
url=$(LANG=C pacman -Qi "$package" | grep "^URL" | awk '{print $3}')
license=$(LANG=C pacman -Qi "$package" | grep "^Licenses" | cut -d ':' -f2- | sed 's/^ //')
arch=$(uname -m)
size=$(du -bs "$pkgDir" | cut -f1)
buildDate=$(date +%s)
packager="$(whoami) <$(whoami)@$(hostname)>"
depends=$(LANG=C pacman -Qi "$package" | grep "^Depends On" | cut -d ':' -f2- | sed 's/^ //' | sed 's/None//')

cat <<EOF >"$pkgInfo"
# Generated by recreate-package.sh v1.1.0
pkgname = $package
pkgver = $pkgVer
pkgdesc = $pkgDesc
url = $url
builddate = $buildDate
packager = $packager
size = $size
arch = $arch
license = $license
EOF

# Add dependencies
if [ -n "$depends" ]; then
    echo "$depends" | tr ' ' '\n' | while read -r depend; do
        if [ -n "$depend" ]; then
            echo "depend = $depend" >>"$pkgInfo"
        fi
    done
fi

# Step 5: Create the .MTREE file
printMsg "Creating .MTREE file..."
cd "$pkgDir" || exit 1
LANG=C bsdtar -c --format=mtree \
    --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
    . >"$mTree"

if [ $? -ne 0 ]; then
    printErr "Error creating .MTREE file."
    exit 1
fi

# Generate date and time in the desired format
date=$(date +%y.%m.%d)
time=$(date +%H%M)

# Define the final package name with date, time, and architecture
finalPackage="${outputDir}/${package}-${pkgVer}-${arch}.pkg.tar.zst"

# Step 6: Package the files using fakeroot
printMsg "Creating the package..."
cd "$pkgDir" || exit 1
fakeroot -- env LANG=C bsdtar -c --zstd -f "$finalPackage" .PKGINFO .MTREE *

if [ $? -ne 0 ]; then
    printErr "Error creating the package."
    exit 1
fi

# Step 7: Generate the .md5 file
printMsg "Generating .md5 file..."
md5sum "$finalPackage" >"${finalPackage}.md5"
if [ $? -ne 0 ]; then
    printErr "Error generating .md5 file."
    exit 1
fi

# Step 8: Verify the created package
if [ -f "$finalPackage" ]; then
    printOk "Package created successfully: ${finalPackage}"
    printOk ".md5 file created: ${finalPackage}.md5"
    
    # Show the size of the created package
    packageSize=$(du -h "$finalPackage" | cut -f1)
    printOk "Size of created package: ${packageSize}"
    
    printWarn "To install the package, run:"
    echo -e "${cyan}sudo pacman -U $finalPackage${reset}"
else
    printErr "Package was not created."
    exit 1
fi

# Clean up temporary files (optional)
read -p "Do you want to remove temporary files? [y/N]: " response
if [[ "$response" =~ ^([yY])$ ]]; then
    sudo rm -rf "$workDir"
    printOk "Temporary files removed."
else
    printWarn "Temporary files kept in $workDir."
fi

exit 0
